-- RLS scaffold for future backend integration.
-- This file is not executed in the current demo setup.

alter table public.profiles enable row level security;
alter table public.employees enable row level security;
alter table public.vehicles enable row level security;
alter table public.shifts enable row level security;
alter table public.plan_publications enable row level security;
alter table public.absences enable row level security;
alter table public.vacation_requests enable row level security;
alter table public.sickness_reports enable row level security;
alter table public.employee_documents enable row level security;
alter table public.document_submissions enable row level security;
alter table public.notifications enable row level security;
alter table public.tasks enable row level security;
alter table public.customers enable row level security;
alter table public.rides enable row level security;
alter table public.ride_series enable row level security;

create policy if not exists profiles_select_all on public.profiles for select using (true);
create policy if not exists profiles_insert_all on public.profiles for insert with check (true);
create policy if not exists profiles_update_all on public.profiles for update using (true) with check (true);
create policy if not exists employees_select_all on public.employees for select using (true);
create policy if not exists employees_insert_all on public.employees for insert with check (true);
create policy if not exists employees_update_all on public.employees for update using (true) with check (true);
create policy if not exists vehicles_select_all on public.vehicles for select using (true);
create policy if not exists vehicles_insert_all on public.vehicles for insert with check (true);
create policy if not exists vehicles_update_all on public.vehicles for update using (true) with check (true);
create policy if not exists shifts_select_all on public.shifts for select using (true);
create policy if not exists shifts_insert_all on public.shifts for insert with check (true);
create policy if not exists shifts_update_all on public.shifts for update using (true) with check (true);
create policy if not exists plan_publications_select_all on public.plan_publications for select using (true);
create policy if not exists plan_publications_insert_all on public.plan_publications for insert with check (true);
create policy if not exists plan_publications_update_all on public.plan_publications for update using (true) with check (true);
create policy if not exists absences_select_all on public.absences for select using (true);
create policy if not exists absences_insert_all on public.absences for insert with check (true);
create policy if not exists absences_update_all on public.absences for update using (true) with check (true);
create policy if not exists vacation_requests_select_all on public.vacation_requests for select using (true);
create policy if not exists vacation_requests_insert_all on public.vacation_requests for insert with check (true);
create policy if not exists vacation_requests_update_all on public.vacation_requests for update using (true) with check (true);
create policy if not exists sickness_reports_select_all on public.sickness_reports for select using (true);
create policy if not exists sickness_reports_insert_all on public.sickness_reports for insert with check (true);
create policy if not exists sickness_reports_update_all on public.sickness_reports for update using (true) with check (true);
create policy if not exists employee_documents_select_all on public.employee_documents for select using (true);
create policy if not exists employee_documents_insert_all on public.employee_documents for insert with check (true);
create policy if not exists employee_documents_update_all on public.employee_documents for update using (true) with check (true);
create policy if not exists document_submissions_select_all on public.document_submissions for select using (true);
create policy if not exists document_submissions_insert_all on public.document_submissions for insert with check (true);
create policy if not exists document_submissions_update_all on public.document_submissions for update using (true) with check (true);
create policy if not exists notifications_select_all on public.notifications for select using (true);
create policy if not exists notifications_insert_all on public.notifications for insert with check (true);
create policy if not exists notifications_update_all on public.notifications for update using (true) with check (true);
create policy if not exists tasks_select_all on public.tasks for select using (true);
create policy if not exists tasks_insert_all on public.tasks for insert with check (true);
create policy if not exists tasks_update_all on public.tasks for update using (true) with check (true);
create policy if not exists customers_select_all on public.customers for select using (true);
create policy if not exists customers_insert_all on public.customers for insert with check (true);
create policy if not exists customers_update_all on public.customers for update using (true) with check (true);
create policy if not exists rides_select_all on public.rides for select using (true);
create policy if not exists rides_insert_all on public.rides for insert with check (true);
create policy if not exists rides_update_all on public.rides for update using (true) with check (true);
create policy if not exists ride_series_select_all on public.ride_series for select using (true);
create policy if not exists ride_series_insert_all on public.ride_series for insert with check (true);
create policy if not exists ride_series_update_all on public.ride_series for update using (true) with check (true);
